<template>
   <div id="Nosotros">
    <header>
           <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->
       <div class="wave" style="height: 150px; overflow: hidden;">
         <svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;">
            <path d="M0.00,49.99 C150.00,150.00 349.20,-49.99 500.00,49.99 L500.00,150.00 L0.00,150.00 Z"
                    style="stroke: none; fill: #fff;">
            </path>
         </svg>
       </div>
 
       <section class="textos-header">
            <h1>Potencia tus ventas al menos un 200%</h1>
            <h2>Con una pagina web potente</h2>
        </section>
      </header>
    <main>
        <section class="contenedor sobre-nosotros">
            <h2 class="titulo">Nuestros productos</h2>
            <div class="contenedor-sobre-nosotros">
                <img src="../img/ilustracion.png" alt="" class="image-about-us">
                <div class="contenido-textos">
                    <h3><span>1</span>Los mejores Productos</h3>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur officia minus excepturi
                        accusantium earum commodi blanditiis dolores, libero architecto, tempora adipisci reiciendis
                        quisquam enim alias deserunt maxime praesentium sint. Autem?</p>
                    <h3><span>2</span>Los mejores Productos</h3>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur officia minus excepturi
                        accusantium earum commodi blanditiis dolores, libero architecto, tempora adipisci reiciendis
                        quisquam enim alias deserunt maxime praesentium sint. Autem?</p>
                      <h3><span>3</span>Los mejores Productos</h3>
                    <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Pariatur officia minus excepturi
                        accusantium earum commodi blanditiis dolores, libero architecto, tempora adipisci reiciendis
                        quis</p>
                </div>
            </div>
        </section>
        <section class="portafolio-contenedor">
              <h2 class="titulo1">"Nutrición Saludable a un click"</h2>
                <div class="galeria-port">
                    <div class="imagen-port">
                        <img src="../img/colac.webp" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                
                    <div class="imagen-port">
                        <img src="../img/imagen4.webp" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                       <div class="imagen-port">
                        <img src="../img/ensalada.jpeg" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                            <div class="imagen-port">
                        <img src="../img/ver.jpeg" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                    
                    <div class="imagen-port">
                        <img src="../img/ejercicio1.webp" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                      <div class="imagen-port">
                        <img src="../img/imagen3.jpeg" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                     <div class="imagen-port">
                        <img src="../img/emb1.jpg" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
                    
                    <div class="imagen-port">
                        <img src="../img/imagen2.jpeg" alt="">
                        <div class="hover-galeria">
                            <img src="https://img.icons8.com/nolan/64/target-weld.png" />
                            <p>Nuestro Trabajo</p>
                        </div>
                    </div>
            </div>
          </section>
          <section class="clientes contenedor">
            <h2 class="titulo1">"Lo que dicen nuestros clientes"</h2>
            <div class="cards">
                <div class="card">
                    <img src="../img/plana1.jpg" alt="">
                    <div class="contenido-texto-card">
                        <h4>Nombre</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, hic!</p>
                    </div>
                </div>
                <div class="card">
                    <img src="../img/plana1.jpg" alt="">
                    <div class="contenido-texto-card">
                        <h4>Nombre</h4>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo, hic!</p>
                    </div>
                </div>
            </div>
       </section>
            <section class="about-services">
              <h2 class="titulo1">"Nuestros Servicios"</h2>
                <div class="servicio-cont">
                    <div class="servicio-ind">
                        <img src="../img/nutricion.jpg" alt="">
                        <h3>Plan alimenticio personalizado</h3>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, libero.</p>
                    </div>
                    <div class="servicio-ind">
                        <img src="../img/ilustracion2.jpg" alt="">
                        <h3>Recomendaciones de ejercicio diario</h3>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, libero.</p>
                    </div>
                    <div class="servicio-ind">
                        <img src="../img/ilustracion3.png" alt="">
                        <h3>Recetas de comida saludable</h3>
                        <p>Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, libero.</p>
                    </div>
                </div>
        </section>
    </main> 
       <footer>
        <div class="contenedor-footer">
            <div class="content-foo">
                <h4>Telefono</h4>
                <p>12345678</p>
            </div>


            <div class="content-foo">
                <h4>Email</h4>
                <p>nutri.consulta@gmail.com</p>
            </div>


            <div class="content-foo">
                <h4>Facebook</h4>
                <p>Nutrici-onClick</p>
            </div>
        </div>

          <h2 class="titulo-final">&copy; Judith Castillo | Nutrióloga</h2>
      </footer>
  </div>
</template>

<style scoped lang="stylus">

#nosotros {
  font-family:'open sans'
  box-sizing border-box
  margin 0
  -webkit-font-smoothing antialiased
  -moz-osx-font-smoothing grayscale
}
header{
  width: 100%;
  height: 700px;
  background: #4e71bc;
                      /* TRANSPARENCIA IMG PRINCIPAL */
   /* fallback for old browsers */
background: -webkit-linear-gradient(to top, hsla(188, 44%, 42%, 0.616), hsla(240, 10%, 47%, 0.616), hsla(340, 39%, 48%, 0.616)), url(../img/principal.jpg);
  /* Chrome 10-25, Safari 5.1-6 */
background: linear-gradient(to top, hsla(188, 44%, 42%, 0.616), hsla(240, 10%, 47%, 0.616), hsla(340, 39%, 48%, 0.616)), url(../img/principal.jpg);
 /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
 background-size: cover;
 background-attachment: fixed;
 position: relative; 
 padding-bottom: 100px;
}
.header .textos-header{
    display: flex;
    height: 400px;
    width: 100%;
    align-items: center;
    justify-content:center;
    flex-direction: column;
    text-align: center;
}


.wave{
    position: absolute;
    bottom: 0;
    width: 100%;
}  
 .textos-header{
    display: flex;
    height: 550px;
    width: 100%;
    align-items: center;
    justify-content:center;
    flex-direction: column;
    text-align: center;
}
.textos-header h1{
    font-size: 50px;
    color: #fff;
}
.textos-header h2{
    font-size: 30px;
    font-weight: 300;
    color: #fff;
}
    
.contenedor{
    padding: 60px;
    width: 90%;
    max-width: 900px;
    margin: auto;
    overflow: hidden;

}
.titulo{
 color: #642a73; 
 font-size: 30px;
 text-align: center; 
 margin-top: 50px
 margin-bottom: 50px; 
}
.titulo1{
 color: #642a73; 
 font-size: 30px;
 text-align: center; 
 margin-top: 60px
 margin-bottom: 50px; 
}

/*-----About us ------*/
.main .sobre-nosotros{
   padding: 30px 0 60px 0; 
}
.contenedor-sobre-nosotros{
   display: flex;
   justify-content: space-evenly;
}
.contenedor-sobre-nosotros img{
   width: 60%
}
.sobre-nosotros .contenido-textos{
    width: 48%;
}
.contenedor h2{
    padding-top 10px
}

.contenido-textos h3{
    margin-bottom: 15px;
}
.contenido-textos h3 span{
    background: #4d0686;
    color: #fff;
    border-radius: 50%;
    display: inline-block;
    text-align: center;
    width: 40px;
    height: 40px;
    padding: 4px;
    box-shadow: 0 0 6px 0 rgba(0, 0, 0, .5);
    margin-right: 5px;
}
.contenido-textos p{
    padding: 0px 0px 30px 15px;
    font-weight: 300;
    text-align: justify;
}
/* -------Galería --------*/
.portafolio-contenedor{
    background: #f2f2f2;
    
}
.galeria-port{
    display: flex;
    justify-content: space-evenly;
    flex-wrap: wrap;
    background: 0 0 6px 0 rgba(0, 0, 0, .5);
}

.imagen-port{
    width: 20%;
    margin-left 20px
    margin-bottom: 40px;
    box-shadow:  0 0 15px 1px #0000007
    overflow: hidden;
    position: relative;
    cursor: pointer;  
}

.imagen-port > img{
 width: 90%;
 height: 90%;
 border-radius: 10px;
 object-fit: cover;
 display: block;
}
.hover-galeria{
    position: absolute;
    width: 90%;
    height: 90%;
    border-radius: 10px;
    top: 0;
    transform: scale(0);
    background: hsla(273,91%, 27%, 0.7);
    transition: transform .5s;
    display: flex;
    justify-content: center;
    align-items: center;
    flex-direction: column;
}
.hover-galeria img{
    width: 50px;
}
.hover-galeria p{
    color: #fff;
}
.imagen-port:hover .hover-galeria{
    transform: scale(1);
}
/*----Clients ---*/
.cards{
    display: flex;
    justify-content: space-evenly;
    

}
.cards .card{
  background: #4d0686;
  display: flex;
  width: 46%;
  height: 230px;
  align-items: center;
  justify-content: space-evenly;
  border-radius: 5px;
  box-shadow: 0 0 6px 0 rgba(0, 0, 0, 0.6);
}
.cards .card img {
    width: 100px;
    height: 200px;
    object-fit: cover;
    border: 3px solid #fff;
    border-radius: 50%;
    margin-top: 30px;
    display: block;
}
.cards .card > .contenido-texto-card{
    width: 60%;
    color: #fff;
}
.cards .card > .contenido-texto-card p{
   font-weight: 300;
    padding-top: 5px;
}
/*   Our team */
.about-services{
    background: #f2f2f2;
    padding-bottom: 30px;
}
.servicio-cont{
    display: flex;
    justify-content: space-between;
    align-items: center;
}
.servicio-ind{
    width: 28%;
    text-align: center;
}
.servicio-ind img{
    width: 80%;
}
.servicio-ind h3{
   margin: 10px 0; 
}
.servicio-ind p{
    font-weight: 300;
    text-align: justify;
}
/*   Footer*/
footer{
    background: #414141;
    padding: 60px 0 30px 0;
    margin: auto;
    overflow: hidden;
}
.contenedor-footer{
    display: flex;
    width: 90%;
    justify-content: space-evenly;
    margin: auto;
    padding-bottom: 50px;
    border-bottom: 1px solid #ccc;
}
.content-foo{
    text-align: center;
}
.content-foo h4{
    color: #fff;
    border-bottom: 3px solid #af20d3;
    padding-bottom: 5px;
    margin-bottom: 10px;
}
.content-foo h4{
    color: #ccc;
}
.content-foo p{
    color: #f2f2f2
}
.titulo-final{
    text-align: center;
    font-size: 24px;
    margin: 20px 0 0 0;
    color: #9e9797;
}
@media screen and (max-width:900px){
    header{
      background-position: center;  
    }
    .contenedor-sobre-nosotros{
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }.sobre-nosotros .contenido-textos{
        width: 90%;

    }
    .imagen-about-us{
        width: 90%;
    }

    /* Galeria*/
    .imagen-port{
        width: 44%;
    }
    /*clientes*/
    .cards{
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .cards .card {
        width: 90%;
    }
    .cards .card:first-child{
       margin-bottom: 30px;
    }
    /*servicios*/
    .servicio-cont{
        justify-content: center;
        flex-direction: column;
    }
    .servicio-ind{
        width: 100%;
        text-align: center;
    }
    .servicio-ind:nth-child(1), .servicio-ind:nth-child(2){
        margin-bottom: 60px;
    }
    .servicio-ind img{
        width: 80%;
    }

}
@media screen and (max-width:500px){
    nav{
       text-align: center;
       padding: 30px 0 0 0;
   }
 
   .textos-header h1{
       font-size: 35px;
   }
   .textos-header h2 {
       font-size: 20px;
   }
   /*ABOUT US */
   .imagen-about-us{
       border-bottom: 60PX;
       width: 99%;
   }
   .contenedor h3{
       font-size: 20px;
   }
   .contenedor-sobre-nosotros img{
   width: 60%
}

   .sobre-nosotros .contenido-textos{
       width: 95%;
   }
   /*Galería*/
   .imagen-port{
       width: 90%;
   }
   /*Clients*/
   .titulo1{
       font-size 25px
       margin-top 0px
    
   }
   .cards .card{
    width: 240px
    height: 270px;
    display: flex;
    flex-direction: column;
    align-items: center;
   }
   .cards .card img{
       width: 90px;
       height: 80px;
   }
   .servicio-ind h3{
 font-size: 25px

}
   /*Footer*/
   .contenedor-footer{
       flex-direction: column;
       border: none;
   }
   .content-foo{
       margin-bottom: 20px;
       text-align: center;
   }
   .content-foo h4{
       border: none;
   }
   .content-foo p{
    color: #ccc;
    border-bottom: 1px solid #f2f2f2;
    padding-bottom: 20px;
   }
   .titulo-final{
       font-size: 20px;
   }
   
} 
</style>
